#!/bin/bash

SOFTWARE="./software"
RCFILES="./rcfiles"

case "$1" in
    -d)
	# Add neccessary repositories
	ppafile="./ppa"
	while read -r line; do
	    ppa="$line"
	    echo "add-apt-repository -y $ppa"
	done < "$ppafile"

	# Install software with apt
	aptfile="$SOFTWARE/apt"
	software=""
	while read -r line; do
	    software="$software $line"
	done < "$aptfile"
	echo "apt install $software"

	# Install software with pip
	pipfile="$SOFTWARE/pip"
	software=""
	while read -r line; do
	    software="$software $line"
	done < "$pipfile"
	echo "pip3 install $software"
	;;
    *)
	# Add neccessary repositories
	ppafile="./ppa"
	while read -r line; do
	    ppa="$line"
	    eval "add-apt-repository -y $ppa"
	done < "$ppafile"

	# Update all software
	apt update && apt upgrade && apt dist-upgrade

	# Install software with apt
	aptfile="$SOFTWARE/apt"
	software=""
	while read -r line; do
	    software="$software $line"
	done < "$aptfile"
	eval "apt install $software"

	# Install software with pip
	pipfile="$SOFTWARE/pip"
	software=""
	while read -r line; do
	    software="$software $line"
	done < "$pipfile"
	eval "pip3 install $software"

	# Install oh-my-zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

	# Replace .zshrc and .nvimrc
	cp $RCFILES/.* $HOME
	;;
esac
